var warArray = [					
['0',	'American Revolutionary War',	'US Fights the British Empire, and wins independance in 1783.',	'1775',	'1783',	'https://en.wikipedia.org/wiki/American_Revolutionary_War'],
['1',	'Cherokee–American wars',	'The Cherokee–American wars, also known as the Chickamauga Wars, were a series of back-and-forth raids, campaigns, ambushes, minor skirmishes, and several full-scale frontier battles in the Old Southwest from 1776 to 1795 between the Cherokee and American settlers on the frontier',	'1776',	'1795',	'https://en.wikipedia.org/wiki/Cherokee–American_wars'],
['2',	'Northwest Indian War',	'The Northwest Indian War, also known as the Ohio War, Little Turtle\u0027s War, and by other names, was a war between the United States and a confederation of numerous Native American tribes, with support from the British, for control of the Northwest Territory.',	'1785',	'1793',	'https://en.wikipedia.org/wiki/Northwest_Indian_War'],
['3',	'Shays\u0027 Rebellion',	'Shays\u0027 Rebellion was an armed uprising in Western Massachusetts in opposition to a debt crisis among the citizenry and the state government’s increased efforts to collect taxes both on individuals and their trades; the fight took place mostly in and around Springfield during 1786 and 1787.',	'1786',	'1787',	'https://en.wikipedia.org/wiki/Shays%27_Rebellion'],
['4',	'Whiskey Rebellion',	'The Whiskey Rebellion was a tax protest in the United States beginning in 1791 and ending in 1794 during the presidency of George Washington, ultimately under the command of American Revolutionary war veteran Major James McFarlane.',	'1791',	'1794',	'https://en.wikipedia.org/wiki/Whiskey_Rebellion'],
['5',	'Quasi-War',	'The Quasi-War was an undeclared war fought almost entirely at sea between the United States and France from 1798 to 1800, which broke out during the beginning of John Adams\u0027s presidency.',	'1798',	'1800',	'https://en.wikipedia.org/wiki/Quasi-War'],
['6',	'Fries Rebellion',	'The Fries Rebellion was an armed tax revolt among Pennsylvania Dutch farmers between 1799 and 1800. It was the third of three tax-related rebellions in the 18th century United States, the earlier two being Shays\u0027 Rebellion (central and western Massachusetts, 1786–87) and the Whiskey Rebellion (western Pennsylvania, 1794).',	'1799',	'1800',	'https://en.wikipedia.org/wiki/Fries_Rebellion'],
['7',	'First Barbary War',	'The Tripolitanian War and the Barbary Coast War, was the first of two Barbary Wars, in which the United States and Sweden fought against the four North African states known collectively as the "Barbary States".',	'1801',	'1805',	'https://en.wikipedia.org/wiki/First_Barbary_War'],
['8',	'1811 German Coast uprising',	'The 1811 German Coast uprising was a revolt of black slaves in parts of the Territory of Orleans on January 8–10, 1811. While the slave insurgency was the largest in US history, the rebels killed only two white men. Confrontations with militia and executions after trial killed 95 black people.',	'1811',	'1811',	'https://en.wikipedia.org/wiki/1811_German_Coast_uprising'],
['9',	'Tecumseh\u0027s War',	'Tecumseh\u0027s War or Rebellion was a conflict between the United States and an American Indian confederacy led by the Shawnee leader Tecumseh in the Indiana Territory.',	'1810',	'1813',	'https://en.wikipedia.org/wiki/Tecumseh%27s_War'],
['10',	'War of 1812',	'The War of 1812 was a conflict fought between the United States and the United Kingdom, with their respective allies, from June 1812 to February 1815. Historians in Britain often see it as a minor theatre of the Napoleonic Wars; historians in the United States and Canada see it as a war in its own right.',	'1812',	'1815',	'https://en.wikipedia.org/wiki/War_of_1812'],
['11',	'Creek War',	'Also known as the Red Stick War and the Creek Civil War, was a regional war between opposing Creek factions, European empires and the United States, taking place largely in today\u0027s Alabama and along the Gulf Coast. The major conflicts of the war took place between state militia units and the "Red Stick" Creeks.',	'1813',	'1814',	'https://en.wikipedia.org/wiki/Creek_War'],
['12',	'Second Barbary War',	'The Second Barbary War was fought between the United States and the North African Barbary Coast states of Tripoli, Tunis, and Ottoman Algeria. The war ended when the United States Senate ratified Commodore Stephen Decatur’s Algerian treaty on December 5, 1815.',	'1815',	'1815',	'https://en.wikipedia.org/wiki/Second_Barbary_War'],
['13',	'First Seminole War',	'There is no consensus about the beginning and ending dates for the First Seminole War. The U.S. Army Infantry indicates that it lasted from 1814 until 1819.',	'1814',	'1819',	'https://en.wikipedia.org/wiki/Seminole_Wars#First_Seminole_War'],
['14',	'Texas–Indian Wars',	'The Texas–Indian wars were a series of 19th-century conflicts between settlers in Texas and the Southern Plains Indians. These conflicts began when the first wave of European-American settlers moved into Spanish Texas. They continued through Texas\u0027s time as part of Mexico, when more Europeans and Anglo-Americans arrived, to the subsequent declaration of independence by the Republic of Texas. The conflicts did not end until thirty years after Texas joined the United States.',	'1820',	'1875',	'https://en.wikipedia.org/wiki/Texas%E2%80%93Indian_wars'],
['15',	'Arikara War',	'The Arikara War was an armed conflict between the United States, their allies from the Sioux (or Dakota) tribe and Arikara Native Americans that took place in the summer of 1823, along the Missouri River in present-day South Dakota. It was the first Indian war west of the Missouri fought by the U.S. Army and its only conflict ever with the Arikara.',	'1823',	'1823',	'https://en.wikipedia.org/wiki/Arikara_War'],
['16',	'Aegean Sea anti-piracy operations of the United States',	'Aegean Sea anti-piracy operations began in 1825 when the United States government dispatched a squadron of ships to suppress Greek piracy in the Aegean Sea',	'1825',	'1828',	'https://en.wikipedia.org/wiki/Aegean_Sea_anti-piracy_operations_of_the_United_States'],
['17',	'Winnebago War',	'The Winnebago War was a brief conflict that took place in 1827 in the Upper Mississippi River region of the United States, primarily in what is now the state of Wisconsin. Not quite a war, the hostilities were limited to a few attacks on American civilians by a portion of the Winnebago (or Ho-Chunk) Native American tribe.',	'1827',	'1827',	'https://en.wikipedia.org/wiki/Winnebago_War'],
['18',	'First Sumatran expedition',	'The First Sumatran expedition, which featured the Battle of Quallah Battoo in 1832, was a punitive expedition by the United States Navy against the village of Kuala Batee, presently a subdistrict in Southwest Aceh Regency. The reprisal was in response to the massacre of the crew of the merchantman Friendship a year earlier. ',	'1832',	'1832',	'https://en.wikipedia.org/wiki/First_Sumatran_expedition'],
['19',	'Black Hawk War',	'The Black Hawk War was a brief conflict between the United States and Native Americans led by Black Hawk, a Sauk leader. The war erupted soon after Black Hawk and a group of Sauks, Meskwakis, and Kickapoos, known as the "British Band", crossed the Mississippi River, into the U.S. state of Illinois, from Iowa Indian Territory in April 1832. Black Hawk\u0027s motives were ambiguous, but he was apparently hoping to avoid bloodshed while resettling on tribal land that had been ceded to the United States in the disputed 1804 Treaty of St. Louis.',	'1832',	'1832',	'https://en.wikipedia.org/wiki/Black_Hawk_War'],
['20',	'Texas Revolution',	'The Texas Revolution was a rebellion of colonists from the United States and Tejanos in putting up armed resistance to the centralist government of Mexico. While the uprising was part of a larger one that included other provinces opposed to the regime of President Antonio López de Santa Anna, the Mexican government believed the United States had instigated the Texas insurrection with the goal of annexation.',	'1835',	'1836',	'https://en.wikipedia.org/wiki/Texas_Revolution'],
['21',	'Second Seminole War',	'The Second Seminole War was a conflict in Florida between various groups of Native Americans collectively known as Seminoles and the United States, part of a series of conflicts called the Seminole Wars. The Second Seminole War, often referred to as the Seminole War, is regarded as the longest and most costly of the Indian conflicts of the United States.',	'1835',	'1842',	'https://en.wikipedia.org/wiki/Second_Seminole_War'],
					
					
					
					
					
					
					
					
];					